---
# This playbook contains tasks to configure WordPress

- include_vars: ../../mysql/defaults/main.yml

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    owner: root
    group: root
    mode: 0777
    copy: no


- name: Copy the sample configuration file for WordPress
  command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
  args:
    creates: /var/www/html/wordpress/wp-config.php

- name: Update Wordpress configuration file
  lineinfile:
    name: /usr/share/nginx/wordpress/wp-config.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { 'regexp' : "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
    - { 'regexp' : "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
    - { 'regexp' : "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
    - { 'regexp' : "define\\('DB_HOST', '(.)+'\\);", 'line': "define('DB_HOST', 'localhost');"}
...
