name: Deploy WordPress Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      

      - name: Deploy and Configure LEMP Stack
        run: |
          ansible-playbook -i inventory install-lemp.yml
       
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          
    
